version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - ./data:/data
    network_mode: host
    dns:
      - 1.1.1.1
  redis:
    image: redis:latest

volumes:
  data: {}
